"use client";
import { useState } from "react";
import { api, type DNA, type Explanation } from "@/lib/atlas-api";
export function ModelView({ states }: { states: DNA[] }) {
  const [selected, setSelected] = useState<string | null>(null);
  const [explanation, setExplanation] = useState<Explanation | null>(null);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  async function inspect(id: string) { if (busy) return; setSelected(id); setBusy(true); setError(""); setExplanation(null); try {setExplanation(await api<Explanation>(`/learning-dna/me/${id}/explanation`));} catch(e) {setError(e instanceof Error ? e.message : "Could not load evidence.");} finally {setBusy(false);} }
  return <section id="learning-dna" className="model-section"><div className="section-heading"><div><p className="eyebrow">STUDENT MODEL / CURRENT STATE</p><h2>Learning DNA</h2></div><span className="outline-tag">{states.length ? "MEASURED FROM EVIDENCE" : "AWAITING MEASUREMENT"}</span></div><div className="model-grid"><div className="panel coordinate-panel"><p className="eyebrow">MASTERY × PROBLEM SOLVING</p><svg viewBox="0 0 500 350" role="img" aria-label="Current concept mastery plotted against problem-solving score; no historical or simulated points">
    {[0,25,50,75,100].map(n => <g key={n}><path d={`M60 ${290-n*2.4} H460 M${60+n*4} 50 V290`} stroke="currentColor" opacity=".13" /><text x="45" y={295-n*2.4} textAnchor="end">{n}</text><text x={60+n*4} y="312" textAnchor="middle">{n}</text></g>)}
    <text x="260" y="340" textAnchor="middle">Concept mastery (%)</text><text transform="translate(15 170) rotate(-90)" textAnchor="middle">Problem-solving score (%)</text>
    {states.map((s,i) => <g key={s.concept_id}><circle cx={60+s.concept_mastery*4} cy={290-s.problem_solving_score*2.4} r={6+Math.min(s.evidence_count,10)/2} fill="var(--accent)" fillOpacity=".45" stroke="var(--accent)" /><text x={Math.min(440,70+s.concept_mastery*4)} y={Math.max(16,282-s.problem_solving_score*2.4-i*13)} fill="var(--foreground)">{s.concept_code.split("_")[1]}</text><title>{s.concept_name}: mastery {s.concept_mastery}%, problem solving {s.problem_solving_score}%, {s.evidence_count} observations</title></g>)}
    {!states.length && <text x="260" y="170" textAnchor="middle" fill="var(--muted)">No observations yet</text>}
    </svg><p className="muted">Each point is a measured concept. Point size reflects evidence count. No trained classifier or historical trajectory is represented.</p></div><div className="panel model-readings"><p className="eyebrow">INSPECT THE EVIDENCE</p>{!states.length ? <><h3>Your model starts with evidence.</h3><p className="muted">Complete a diagnostic to see mastery, accuracy, problem-solving performance, hint dependence, and evidence confidence.</p></> : states.map(s => <div className="reading" key={s.concept_id}><button disabled={busy} onClick={() => void inspect(s.concept_id)} aria-expanded={selected === s.concept_id}><strong>{s.concept_name}</strong><span>{s.evidence_count} observations ↗</span></button><dl><div><dt>Mastery</dt><dd>{s.concept_mastery.toFixed(1)}%</dd></div><div><dt>Accuracy</dt><dd>{s.accuracy.toFixed(1)}%</dd></div><div><dt>Problem solving</dt><dd>{s.problem_solving_score.toFixed(1)}%</dd></div><div><dt>Evidence confidence</dt><dd>{Math.round(s.confidence_score*100)}%</dd></div><div><dt>Hint dependence</dt><dd>{s.hint_dependence.toFixed(1)}%</dd></div></dl></div>)}
    {busy && <p role="status">Loading supporting evidence…</p>}{error && <p role="alert">{error}</p>}{explanation && <div className="evidence-detail"><h3>Supporting observations</h3><p>{explanation.correct_count} correct · {explanation.incorrect_count} incorrect</p>{explanation.question_type_breakdown.map(b => <p key={b.question_type}>{b.question_type.replaceAll("_", " ")}: {b.correct_count}/{b.count} correct ({b.accuracy}%)</p>)}<p className="muted">{explanation.confidence_explanation}</p></div>}
    </div></div><p className="model-footnote">These are deterministic learning metrics, not validated psychological traits. Evidence confidence describes coverage; it is not your self-reported confidence.</p></section>;
}
